export const programs = [
  {
    id: 1,
    title: "Master of Science in Data Science MSDS",
    category: "Graduate",
    image: "/images/programs.png",
    badge: "Full time",
    duration: "2 Years",
    credits: "16 Credits",
  },
  {
    id: 2,
    title: "Master of Public Health MPH Degree",
    category: "Graduate",
    image: "/images/health.png",
    badge: "Research",
    duration: "2 Years",
    credits: "16 Credits",
  },
  {
    id: 3,
    title: "Bachelor of Business Data Administration BBA",
    category: "Undergraduate",
    image: "/images/sr4.png",
    badge: "Full time",
    duration: "2 Years",
    credits: "16 Credits",
  },
  {
    id: 4,
    title: "Bachelor of Arts in Psychology Degree",
    category: "Undergraduate",
    image: "/images/psychology.png",
    badge: "Part time",
    duration: "2 Years",
    credits: "16 Credits",
  },
  {
    id: 5,
    title: "The Doctor of Engineering (EngD) – A Guide",
    category: "PhD",
    image: "/images/health.png",
    badge: "Full time",
    duration: "3 Years",
    credits: "20 Credits",
  },
  {
    id: 6,
    title: "Integrated PhD Programmes in the UK",
    category: "PhD",
    image: "/images/psychology.png",
    badge: "Research",
    duration: "3 Years",
    credits: "20 Credits",
  },
  {
    id: 7,
    title: "Master of Science in Data Science MSDS",
    category: "Graduate",
    image: "/images/programs.png",
    badge: "Full time",
    duration: "2 Years",
    credits: "16 Credits",
  },
  {
    id: 8,
    title: "Bachelor of Business Data Administration BBA",
    category: "Undergraduate",
    image: "/images/sr4.png",
    badge: "Full time",
    duration: "2 Years",
    credits: "16 Credits",
  },
];
